"""
This type stub file was generated by pyright.
"""

import codecs

"""\
Python 'hex' Codec - 2-digit hex with spaces content transfer encoding.

Encode and decode may be a bit missleading at first sight...

The textual representation is a hex dump: e.g. "40 41"
The "encoded" data of this is the binary form, e.g. b"@A"

Therefore decoding is binary to text and thus converting binary data to hex dump.

"""
HEXDIGITS = ...
def hex_encode(data, errors=...): # -> tuple[<subclass of list and bytes> | bytes | Unknown, int]:
    """'40 41 42' -> b'@ab'"""
    ...

def hex_decode(data, errors=...): # -> tuple[unicode, int]:
    """b'@ab' -> '40 41 42'"""
    ...

class Codec(codecs.Codec):
    def encode(self, data, errors=...): # -> <subclass of list and bytes> | bytes:
        """'40 41 42' -> b'@ab'"""
        ...
    
    def decode(self, data, errors=...): # -> unicode:
        """b'@ab' -> '40 41 42'"""
        ...
    


class IncrementalEncoder(codecs.IncrementalEncoder):
    """Incremental hex encoder"""
    def __init__(self, errors=...) -> None:
        ...
    
    def reset(self): # -> None:
        ...
    
    def getstate(self): # -> int | str:
        ...
    
    def setstate(self, state): # -> None:
        ...
    
    def encode(self, data, final=...): # -> <subclass of list and bytes> | bytes:
        """\
        Incremental encode, keep track of digits and emit a byte when a pair
        of hex digits is found. The space is optional unless the error
        handling is defined to be 'strict'.
        """
        ...
    


class IncrementalDecoder(codecs.IncrementalDecoder):
    """Incremental decoder"""
    def decode(self, data, final=...): # -> unicode:
        ...
    


class StreamWriter(Codec, codecs.StreamWriter):
    """Combination of hexlify codec and StreamWriter"""
    ...


class StreamReader(Codec, codecs.StreamReader):
    """Combination of hexlify codec and StreamReader"""
    ...


def getregentry(): # -> CodecInfo:
    """encodings module API"""
    ...

