"""
This type stub file was generated by pyright.
"""

from serial.tools import list_ports_common

class SysFS(list_ports_common.ListPortInfo):
    """Wrapper for easy sysfs access and device info"""
    def __init__(self, device) -> None:
        ...
    
    def read_line(self, *args): # -> str | None:
        """\
        Helper function to read a single line from a file.
        One or more parameters are allowed, they are joined with os.path.join.
        Returns None on errors..
        """
        ...
    


def comports(include_links=...): # -> list[SysFS]:
    ...

if __name__ == '__main__':
    ...
