"""
This type stub file was generated by pyright.
"""

"""\
The ``comports`` function is expected to return an iterable that yields tuples
of 3 strings: port name, human readable description and a hardware ID.

As currently no method is known to get the second two strings easily, they are
currently just identical to the port name.
"""
plat = ...
if plat[: 5] == 'linux':
    ...
else:
    ...
if __name__ == '__main__':
    ...
