"""
This type stub file was generated by pyright.
"""

import ctypes

iokit = ...
cf = ...
kIOMasterPortDefault = ...
kCFAllocatorDefault = ...
kCFStringEncodingMacRoman = ...
kCFStringEncodingUTF8 = ...
kUSBVendorString = ...
kUSBSerialNumberString = ...
io_name_size = ...
KERN_SUCCESS = ...
kern_return_t = ctypes.c_int
kCFNumberSInt8Type = ...
kCFNumberSInt16Type = ...
kCFNumberSInt32Type = ...
kCFNumberSInt64Type = ...
def get_string_property(device_type, property): # -> Any | None:
    """
    Search the given device for the specified string property

    @param device_type Type of Device
    @param property String to search for
    @return Python string containing the value, or None if not found.
    """
    ...

def get_int_property(device_type, property, cf_number_type): # -> int | None:
    """
    Search the given device for the specified string property

    @param device_type Device to search
    @param property String to search for
    @param cf_number_type CFType number

    @return Python string containing the value, or None if not found.
    """
    ...

def IORegistryEntryGetName(device): # -> Any | None:
    ...

def IOObjectGetClass(device): # -> Any:
    ...

def GetParentDeviceByType(device, parent_type): # -> c_void_p | None:
    """ Find the first parent of a device that implements the parent_type
        @param IOService Service to inspect
        @return Pointer to the parent type, or None if it was not found.
    """
    ...

def GetIOServicesByType(service_type): # -> list[Unknown]:
    """
    returns iterator over specified service_type
    """
    ...

def location_to_string(locationID): # -> str:
    """
    helper to calculate port and bus number from locationID
    """
    ...

class SuitableSerialInterface:
    ...


def scan_interfaces(): # -> list[Unknown]:
    """
    helper function to scan USB interfaces
    returns a list of SuitableSerialInterface objects with name and id attributes
    """
    ...

def search_for_locationID_in_interfaces(serial_interfaces, locationID): # -> None:
    ...

def comports(include_links=...): # -> list[Unknown]:
    ...

if __name__ == '__main__':
    ...
