"""
This type stub file was generated by pyright.
"""

def numsplit(text): # -> list[Unknown]:
    """\
    Convert string into a list of texts and numbers in order to support a
    natural sorting.
    """
    ...

class ListPortInfo:
    """Info collection base class for serial ports"""
    def __init__(self, device, skip_link_detection=...) -> None:
        ...
    
    def usb_description(self): # -> str:
        """return a short string to name the port based on USB info"""
        ...
    
    def usb_info(self): # -> str:
        """return a string with USB related information about device"""
        ...
    
    def apply_usb_info(self): # -> None:
        """update description and hwid from USB data"""
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __getitem__(self, index): # -> Unknown | str:
        """Item access: backwards compatible -> (port, desc, hwid)"""
        ...
    


def list_links(devices): # -> list[Unknown]:
    """\
    search all /dev devices and look for symlinks to known ports already
    listed in devices.
    """
    ...

if __name__ == '__main__':
    ...
