"""
This type stub file was generated by pyright.
"""

import os

"""\
This module will provide a function called comports that returns an
iterable (generator or list) that will enumerate available com ports. Note that
on some systems non-existent ports may be listed.

Additionally a grep function is supplied that can be used to search for ports
based on their descriptions or hardware ID.
"""
if os.name == 'nt':
    ...
else:
    ...
def grep(regexp, include_links=...): # -> Generator[ListPortInfo, None, None]:
    """\
    Search for ports using a regular expression. Port name, description and
    hardware ID are searched. The function returns an iterable that returns the
    same tuples as comport() would do.
    """
    ...

def main(): # -> None:
    ...

if __name__ == '__main__':
    ...
