"""
This type stub file was generated by pyright.
"""

import os

def key_description(character): # -> str:
    """generate a readable description for a key"""
    ...

class ConsoleBase:
    """OS abstraction for console (input/output codec, no echo)"""
    def __init__(self) -> None:
        ...
    
    def setup(self): # -> None:
        """Set console to read single characters, no echo"""
        ...
    
    def cleanup(self): # -> None:
        """Restore default console settings"""
        ...
    
    def getkey(self): # -> None:
        """Read a single key from the console"""
        ...
    
    def write_bytes(self, byte_string): # -> None:
        """Write bytes (already encoded)"""
        ...
    
    def write(self, text): # -> None:
        """Write string"""
        ...
    
    def cancel(self): # -> None:
        """Cancel getkey operation"""
        ...
    
    def __enter__(self): # -> Self@ConsoleBase:
        ...
    
    def __exit__(self, *args, **kwargs): # -> None:
        ...
    


if os.name == 'nt':
    class Out:
        """file-like wrapper that uses os.write"""
        def __init__(self, fd) -> None:
            ...
        
        def flush(self): # -> None:
            ...
        
        def write(self, s): # -> None:
            ...
        
    
    
    class Console(ConsoleBase):
        fncodes = ...
        navcodes = ...
        def __init__(self) -> None:
            ...
        
        def __del__(self): # -> None:
            ...
        
        def getkey(self): # -> str:
            ...
        
        def cancel(self): # -> None:
            ...
        
    
    
else:
    ...
class Transform:
    """do-nothing: forward all data unchanged"""
    def rx(self, text):
        """text received from serial port"""
        ...
    
    def tx(self, text):
        """text to be sent to serial port"""
        ...
    
    def echo(self, text):
        """text to be sent but displayed on console"""
        ...
    


class CRLF(Transform):
    """ENTER sends CR+LF"""
    def tx(self, text):
        ...
    


class CR(Transform):
    """ENTER sends CR"""
    def rx(self, text):
        ...
    
    def tx(self, text):
        ...
    


class LF(Transform):
    """ENTER sends LF"""
    ...


class NoTerminal(Transform):
    """remove typical terminal control codes from input"""
    REPLACEMENT_MAP = ...
    def rx(self, text):
        ...
    
    echo = ...


class NoControls(NoTerminal):
    """Remove all control codes, incl. CR+LF"""
    REPLACEMENT_MAP = ...


class Printable(Transform):
    """Show decimal code for all non-ASCII characters and replace most control codes"""
    def rx(self, text): # -> LiteralString:
        ...
    
    echo = ...


class Colorize(Transform):
    """Apply different colors for received and echo"""
    def __init__(self) -> None:
        ...
    
    def rx(self, text):
        ...
    
    def echo(self, text):
        ...
    


class DebugIO(Transform):
    """Print what is sent and received"""
    def rx(self, text):
        ...
    
    def tx(self, text):
        ...
    


EOL_TRANSFORMATIONS = ...
TRANSFORMATIONS = ...
def ask_for_port(): # -> str:
    """\
    Show a list of ports and ask the user for a choice. To make selection
    easier on systems with long device names, also allow the input of an
    index.
    """
    ...

class Miniterm:
    """\
    Terminal application. Copy data from serial port to console and vice versa.
    Handle special keys from the console to show menu etc.
    """
    def __init__(self, serial_instance, echo=..., eol=..., filters=...) -> None:
        ...
    
    def start(self): # -> None:
        """start worker threads"""
        ...
    
    def stop(self): # -> None:
        """set flag to stop worker threads"""
        ...
    
    def join(self, transmit_only=...): # -> None:
        """wait for worker threads to terminate"""
        ...
    
    def close(self): # -> None:
        ...
    
    def update_transformations(self): # -> None:
        """take list of transformation classes and instantiate them for rx and tx"""
        ...
    
    def set_rx_encoding(self, encoding, errors=...): # -> None:
        """set encoding for received data"""
        ...
    
    def set_tx_encoding(self, encoding, errors=...): # -> None:
        """set encoding for transmitted data"""
        ...
    
    def dump_port_settings(self): # -> None:
        """Write current settings to sys.stderr"""
        ...
    
    def reader(self): # -> None:
        """loop and copy serial->console"""
        ...
    
    def writer(self): # -> None:
        """\
        Loop and copy console->serial until self.exit_character character is
        found. When self.menu_character is found, interpret the next key
        locally.
        """
        ...
    
    def handle_menu_key(self, c):
        """Implement a simple menu / settings"""
        ...
    
    def upload_file(self): # -> None:
        """Ask user for filenname and send its contents"""
        ...
    
    def change_filter(self): # -> None:
        """change the i/o transformations"""
        ...
    
    def change_encoding(self): # -> None:
        """change encoding on the serial port"""
        ...
    
    def change_baudrate(self): # -> None:
        """change the baudrate"""
        ...
    
    def change_port(self): # -> None:
        """Have a conversation with the user to change the serial port"""
        ...
    
    def suspend_port(self): # -> None:
        """\
        open port temporarily, allow reconnect, exit and port change to get
        out of the loop
        """
        ...
    
    def get_help_text(self): # -> str:
        """return the help text"""
        ...
    


def main(default_port=..., default_baudrate=..., default_rts=..., default_dtr=...):
    """Command line tool, entry point"""
    ...

if __name__ == '__main__':
    ...
