"""
This type stub file was generated by pyright.
"""

import serial

"""\
The settings for RS485 are stored in a dedicated object that can be applied to
serial ports (where supported).
NOTE: Some implementations may only support a subset of the settings.
"""
class RS485Settings:
    def __init__(self, rts_level_for_tx=..., rts_level_for_rx=..., loopback=..., delay_before_tx=..., delay_before_rx=...) -> None:
        ...
    


class RS485(serial.Serial):
    """\
    A subclass that replaces the write method with one that toggles RTS
    according to the RS485 settings.

    NOTE: This may work unreliably on some serial ports (control signals not
          synchronized or delayed compared to data). Using delays may be
          unreliable (varying times, larger than expected) as the OS may not
          support very fine grained delays (no smaller than in the order of
          tens of milliseconds).

    NOTE: Some implementations support this natively. Better performance
          can be expected when the native version is used.

    NOTE: The loopback property is ignored by this implementation. The actual
          behavior depends on the used hardware.

    Usage:

        ser = RS485(...)
        ser.rs485_mode = RS485Settings(...)
        ser.write(b'hello')
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def write(self, b): # -> None:
        """Write to port, controlling RTS before and after transmitting."""
        ...
    
    @property
    def rs485_mode(self): # -> None:
        """\
        Enable RS485 mode and apply new settings, set to None to disable.
        See serial.rs485.RS485Settings for more info about the value.
        """
        ...
    
    @rs485_mode.setter
    def rs485_mode(self, rs485_settings): # -> None:
        ...
    


