"""
This type stub file was generated by pyright.
"""

from serial.serialutil import *

sab = ...
def as_byte_array(string):
    ...

class Serial(SerialBase):
    """Serial port implementation for .NET/Mono."""
    BAUDRATES = ...
    def open(self): # -> None:
        """\
        Open port with current settings. This may throw a SerialException
        if the port cannot be opened.
        """
        ...
    
    def close(self): # -> None:
        """Close port"""
        ...
    
    @property
    def in_waiting(self):
        """Return the number of characters currently in the input buffer."""
        ...
    
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    
    def write(self, data): # -> int:
        """Output the given string over the serial port."""
        ...
    
    def reset_input_buffer(self): # -> None:
        """Clear input buffer, discarding all that is in the buffer."""
        ...
    
    def reset_output_buffer(self): # -> None:
        """\
        Clear output buffer, aborting the current output and
        discarding all that is in the buffer.
        """
        ...
    
    @property
    def cts(self):
        """Read terminal status line: Clear To Send"""
        ...
    
    @property
    def dsr(self):
        """Read terminal status line: Data Set Ready"""
        ...
    
    @property
    def ri(self): # -> Literal[False]:
        """Read terminal status line: Ring Indicator"""
        ...
    
    @property
    def cd(self):
        """Read terminal status line: Carrier Detect"""
        ...
    


