"""
This type stub file was generated by pyright.
"""

import termios
from serial.serialutil import SerialBase

class PlatformSpecificBase:
    BAUDRATE_CONSTANTS = ...
    def set_low_latency_mode(self, low_latency_settings):
        ...
    


CMSPAR = ...
plat = ...
if plat[: 5] == 'linux':
    CMSPAR = ...
    TCGETS2 = ...
    TCSETS2 = ...
    BOTHER = ...
    TIOCGRS485 = ...
    TIOCSRS485 = ...
    SER_RS485_ENABLED = ...
    SER_RS485_RTS_ON_SEND = ...
    SER_RS485_RTS_AFTER_SEND = ...
    SER_RS485_RX_DURING_TX = ...
    class PlatformSpecific(PlatformSpecificBase):
        BAUDRATE_CONSTANTS = ...
        def set_low_latency_mode(self, low_latency_settings): # -> None:
            ...
        
    
    
else:
    class PlatformSpecific(PlatformSpecificBase):
        BAUDRATE_CONSTANTS = ...
    
    
TIOCMGET = ...
TIOCMBIS = ...
TIOCMBIC = ...
TIOCMSET = ...
TIOCM_DTR = ...
TIOCM_RTS = ...
TIOCM_CTS = ...
TIOCM_CAR = ...
TIOCM_RNG = ...
TIOCM_DSR = ...
TIOCM_CD = ...
TIOCM_RI = ...
if hasattr(termios, 'TIOCINQ'):
    TIOCINQ = ...
else:
    TIOCINQ = ...
TIOCOUTQ = ...
TIOCM_zero_str = ...
TIOCM_RTS_str = ...
TIOCM_DTR_str = ...
TIOCSBRK = ...
TIOCCBRK = ...
class Serial(SerialBase, PlatformSpecific):
    """\
    Serial port class POSIX implementation. Serial port configuration is
    done with termios and fcntl. Runs on Linux and many other Un*x like
    systems.
    """
    def open(self): # -> None:
        """\
        Open port with current settings. This may throw a SerialException
        if the port cannot be opened."""
        ...
    
    def close(self): # -> None:
        """Close port"""
        ...
    
    @property
    def in_waiting(self): # -> Any:
        """Return the number of bytes currently in the input buffer."""
        ...
    
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    
    def cancel_read(self): # -> None:
        ...
    
    def cancel_write(self): # -> None:
        ...
    
    def write(self, data):
        """Output the given byte string over the serial port."""
        ...
    
    def flush(self): # -> None:
        """\
        Flush of file like objects. In this case, wait until all data
        is written.
        """
        ...
    
    def reset_input_buffer(self): # -> None:
        """Clear input buffer, discarding all that is in the buffer."""
        ...
    
    def reset_output_buffer(self): # -> None:
        """\
        Clear output buffer, aborting the current output and discarding all
        that is in the buffer.
        """
        ...
    
    def send_break(self, duration=...): # -> None:
        """\
        Send break condition. Timed, returns to idle state after given
        duration.
        """
        ...
    
    @property
    def cts(self): # -> Any:
        """Read terminal status line: Clear To Send"""
        ...
    
    @property
    def dsr(self): # -> Any:
        """Read terminal status line: Data Set Ready"""
        ...
    
    @property
    def ri(self): # -> Any:
        """Read terminal status line: Ring Indicator"""
        ...
    
    @property
    def cd(self): # -> Any:
        """Read terminal status line: Carrier Detect"""
        ...
    
    @property
    def out_waiting(self): # -> Any:
        """Return the number of bytes currently in the output buffer."""
        ...
    
    def fileno(self): # -> int | None:
        """\
        For easier use of the serial port instance with select.
        WARNING: this function is not portable to different platforms!
        """
        ...
    
    def set_input_flow_control(self, enable=...): # -> None:
        """\
        Manually control flow - when software flow control is enabled.
        This will send XON (true) or XOFF (false) to the other device.
        WARNING: this function is not portable to different platforms!
        """
        ...
    
    def set_output_flow_control(self, enable=...): # -> None:
        """\
        Manually control flow of outgoing data - when hardware or software flow
        control is enabled.
        WARNING: this function is not portable to different platforms!
        """
        ...
    
    def nonblocking(self): # -> None:
        """DEPRECATED - has no use"""
        ...
    


class PosixPollSerial(Serial):
    """\
    Poll based read implementation. Not all systems support poll properly.
    However this one has better handling of errors, such as a device
    disconnecting while it's in use (e.g. USB-serial unplugged).
    """
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    


class VTIMESerial(Serial):
    """\
    Implement timeout using vtime of tty device instead of using select.
    This means that no inter character timeout can be specified and that
    the error handling is degraded.

    Overall timeout is disabled when inter-character timeout is used.

    Note that this implementation does NOT support cancel_read(), it will
    just ignore that.
    """
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    
    cancel_read = ...


