"""
This type stub file was generated by pyright.
"""

from serial.serialutil import *

def my_import(name): # -> Any:
    ...

def detect_java_comm(names): # -> Any:
    """try given list of modules and return that imports"""
    ...

comm = ...
def device(portnumber):
    """Turn a port number into a device name"""
    ...

class Serial(SerialBase):
    """\
    Serial port class, implemented with Java Communications API and
    thus usable with jython and the appropriate java extension.
    """
    def open(self): # -> None:
        """\
        Open port with current settings. This may throw a SerialException
        if the port cannot be opened.
        """
        ...
    
    def close(self): # -> None:
        """Close port"""
        ...
    
    @property
    def in_waiting(self): # -> comm:
        """Return the number of characters currently in the input buffer."""
        ...
    
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    
    def write(self, data): # -> int:
        """Output the given string over the serial port."""
        ...
    
    def reset_input_buffer(self): # -> None:
        """Clear input buffer, discarding all that is in the buffer."""
        ...
    
    def reset_output_buffer(self): # -> None:
        """\
        Clear output buffer, aborting the current output and
        discarding all that is in the buffer.
        """
        ...
    
    def send_break(self, duration=...): # -> None:
        """Send break condition. Timed, returns to idle state after given duration."""
        ...
    
    @property
    def cts(self): # -> None:
        """Read terminal status line: Clear To Send"""
        ...
    
    @property
    def dsr(self): # -> None:
        """Read terminal status line: Data Set Ready"""
        ...
    
    @property
    def ri(self): # -> None:
        """Read terminal status line: Ring Indicator"""
        ...
    
    @property
    def cd(self): # -> None:
        """Read terminal status line: Carrier Detect"""
        ...
    


