"""
This type stub file was generated by pyright.
"""

from serial.serialutil import SerialBase

class Serial(SerialBase):
    """Serial port implementation for Win32 based on ctypes."""
    BAUDRATES = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def open(self): # -> None:
        """\
        Open port with current settings. This may throw a SerialException
        if the port cannot be opened.
        """
        ...
    
    def close(self): # -> None:
        """Close port"""
        ...
    
    @property
    def in_waiting(self): # -> Any:
        """Return the number of bytes currently in the input buffer."""
        ...
    
    def read(self, size=...): # -> bytes:
        """\
        Read size bytes from the serial port. If a timeout is set it may
        return less characters as requested. With no timeout it will block
        until the requested number of bytes is read.
        """
        ...
    
    def write(self, data): # -> int:
        """Output the given byte string over the serial port."""
        ...
    
    def flush(self): # -> None:
        """\
        Flush of file like objects. In this case, wait until all data
        is written.
        """
        ...
    
    def reset_input_buffer(self): # -> None:
        """Clear input buffer, discarding all that is in the buffer."""
        ...
    
    def reset_output_buffer(self): # -> None:
        """\
        Clear output buffer, aborting the current output and discarding all
        that is in the buffer.
        """
        ...
    
    @property
    def cts(self): # -> bool:
        """Read terminal status line: Clear To Send"""
        ...
    
    @property
    def dsr(self): # -> bool:
        """Read terminal status line: Data Set Ready"""
        ...
    
    @property
    def ri(self): # -> bool:
        """Read terminal status line: Ring Indicator"""
        ...
    
    @property
    def cd(self): # -> bool:
        """Read terminal status line: Carrier Detect"""
        ...
    
    def set_buffer_size(self, rx_size=..., tx_size=...): # -> None:
        """\
        Recommend a buffer size to the driver (device driver can ignore this
        value). Must be called after the port is opened.
        """
        ...
    
    def set_output_flow_control(self, enable=...): # -> None:
        """\
        Manually control flow - when software flow control is enabled.
        This will do the same as if XON (true) or XOFF (false) are received
        from the other device and control the transmission accordingly.
        WARNING: this function is not portable to different platforms!
        """
        ...
    
    @property
    def out_waiting(self): # -> Any:
        """Return how many bytes the in the outgoing buffer"""
        ...
    
    def cancel_read(self): # -> None:
        """Cancel a blocking read operation, may be called from other thread"""
        ...
    
    def cancel_write(self): # -> None:
        """Cancel a blocking write operation, may be called from other thread"""
        ...
    
    @SerialBase.exclusive.setter
    def exclusive(self, exclusive): # -> None:
        """Change the exclusive access setting."""
        ...
    


