"""
This type stub file was generated by pyright.
"""

import serial
import threading
import sys
import time
import traceback
from __future__ import absolute_import

"""\
Support threading with serial ports.
"""
class Protocol:
    """\
    Protocol as used by the ReaderThread. This base class provides empty
    implementations of all methods.
    """
    def connection_made(self, transport): # -> None:
        """Called when reader thread is started"""
        ...
    
    def data_received(self, data): # -> None:
        """Called with snippets received from the serial port"""
        ...
    
    def connection_lost(self, exc): # -> None:
        """\
        Called when the serial port is closed or the reader loop terminated
        otherwise.
        """
        ...
    


class Packetizer(Protocol):
    """
    Read binary packets from serial port. Packets are expected to be terminated
    with a TERMINATOR byte (null byte by default).

    The class also keeps track of the transport.
    """
    TERMINATOR = ...
    def __init__(self) -> None:
        ...
    
    def connection_made(self, transport): # -> None:
        """Store transport"""
        ...
    
    def connection_lost(self, exc): # -> None:
        """Forget transport"""
        ...
    
    def data_received(self, data): # -> None:
        """Buffer received data, find TERMINATOR, call handle_packet"""
        ...
    
    def handle_packet(self, packet):
        """Process packets - to be overridden by subclassing"""
        ...
    


class FramedPacket(Protocol):
    """
    Read binary packets. Packets are expected to have a start and stop marker.

    The class also keeps track of the transport.
    """
    START = ...
    STOP = ...
    def __init__(self) -> None:
        ...
    
    def connection_made(self, transport): # -> None:
        """Store transport"""
        ...
    
    def connection_lost(self, exc): # -> None:
        """Forget transport"""
        ...
    
    def data_received(self, data): # -> None:
        """Find data enclosed in START/STOP, call handle_packet"""
        ...
    
    def handle_packet(self, packet):
        """Process packets - to be overridden by subclassing"""
        ...
    
    def handle_out_of_packet_data(self, data): # -> None:
        """Process data that is received outside of packets"""
        ...
    


class LineReader(Packetizer):
    """
    Read and write (Unicode) lines from/to serial port.
    The encoding is applied.
    """
    TERMINATOR = ...
    ENCODING = ...
    UNICODE_HANDLING = ...
    def handle_packet(self, packet): # -> None:
        ...
    
    def handle_line(self, line):
        """Process one line - to be overridden by subclassing"""
        ...
    
    def write_line(self, text): # -> None:
        """
        Write text to the transport. ``text`` is a Unicode string and the encoding
        is applied before sending ans also the newline is append.
        """
        ...
    


class ReaderThread(threading.Thread):
    """\
    Implement a serial port read loop and dispatch to a Protocol instance (like
    the asyncio.Protocol) but do it with threads.

    Calls to close() will close the serial port but it is also possible to just
    stop() this thread and continue the serial port instance otherwise.
    """
    def __init__(self, serial_instance, protocol_factory) -> None:
        """\
        Initialize thread.

        Note that the serial_instance' timeout is set to one second!
        Other settings are not changed.
        """
        ...
    
    def stop(self): # -> None:
        """Stop the reader thread"""
        ...
    
    def run(self): # -> None:
        """Reader loop"""
        ...
    
    def write(self, data):
        """Thread safe writing (uses lock)"""
        ...
    
    def close(self): # -> None:
        """Close the serial port and exit reader thread (uses lock)"""
        ...
    
    def connect(self): # -> tuple[Self@ReaderThread, Unknown | None]:
        """
        Wait until connection is set up and return the transport and protocol
        instances.
        """
        ...
    
    def __enter__(self): # -> None:
        """\
        Enter context handler. May raise RuntimeError in case the connection
        could not be created.
        """
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        """Leave context: close port"""
        ...
    


if __name__ == '__main__':
    PORT = ...
    class PrintLines(LineReader):
        def connection_made(self, transport): # -> None:
            ...
        
        def handle_line(self, data): # -> None:
            ...
        
        def connection_lost(self, exc): # -> None:
            ...
        
    
    
    ser = ...
    ser = ...
    t = ...
